// Baseplate.Web/src/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router'
import { Button } from '@/components/ui/button'
import {useCreateRoom} from "@/hooks/room-hooks.ts";

export const Route = createFileRoute('/')({
  component: App,
})

function App() {
    const { mutate: createRoom } = useCreateRoom();
  return (
    <div className="flex flex-col justify-start items-center min-h-screen pt-70"> 
      <div className="flex flex-col">
      <Button onClick={createRoom}>Create Room</Button>
      <Button className="mt-2">Join Room</Button>
    </div>
    </div>
  )
}

// Baseplate.Web/src/routes/+page.svelte
<script>
    import {Button} from "$lib/components/ui/button/index.js";
</script>
<div id="home-content" class="flex flex-col justify-start items-center min-h-screen pt-70">
<!--    <h1 class="font-bold text-5xl mb-10">-->
<!--        Baseplate-->
<!--    </h1>-->
    <div id="home-centre-content" class="flex flex-col">
        <Button>Create new Room</Button>
        <Button class="mt-2">Join Existing Room</Button>
    </div>
</div>
